// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Infrastructure.Data;

#nullable disable

namespace MyApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524153804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Anetaresimet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<decimal>("cmimi")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("data_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_mbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("lloji")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Anetaresimet");
                });

            modelBuilder.Entity("MyApp.Domain.Anetaret", b =>
                {
                    b.Property<int>("anetar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("anetar_id"));

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("data_lindjes")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_regjistrimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gjinia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lloji_anetaresimit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefoni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("anetar_id");

                    b.ToTable("Anetaret");
                });

            modelBuilder.Entity("MyApp.Domain.Instruktoret", b =>
                {
                    b.Property<int>("instruktor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("instruktor_id"));

                    b.Property<string>("biografia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("certifikimet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("data_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("specializimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("tarifa_orare")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("telefoni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("instruktor_id");

                    b.ToTable("Instruktoret");
                });

            modelBuilder.Entity("MyApp.Domain.Klasat", b =>
                {
                    b.Property<int>("klasa_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("klasa_id"));

                    b.Property<string>("emri_klases")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("instruktor_id")
                        .HasColumnType("int");

                    b.Property<int>("kapaciteti")
                        .HasColumnType("int");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("salla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("klasa_id");

                    b.ToTable("Klasat");
                });

            modelBuilder.Entity("MyApp.Domain.Workshop", b =>
                {
                    b.Property<int>("workshop_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("workshop_id"));

                    b.Property<double>("cmimi")
                        .HasColumnType("double");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("instruktor_id")
                        .HasColumnType("int");

                    b.Property<int>("kapaciteti")
                        .HasColumnType("int");

                    b.Property<DateTime>("ora_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ora_perfundimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titulli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("workshop_id");

                    b.ToTable("Workshops");
                });
#pragma warning restore 612, 618
        }
    }
}
