// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Infrastructure.Data;

#nullable disable

namespace MyApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524181003_AddNewEntities")]
    partial class AddNewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Anetaresimet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<decimal>("cmimi")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("data_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_mbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("lloji")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Anetaresimet");
                });

            modelBuilder.Entity("MyApp.Domain.Anetaret", b =>
                {
                    b.Property<int>("anetar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("anetar_id"));

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("data_lindjes")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_regjistrimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gjinia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lloji_anetaresimit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefoni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("anetar_id");

                    b.ToTable("Anetaret");
                });

            modelBuilder.Entity("MyApp.Domain.Instruktoret", b =>
                {
                    b.Property<int>("instruktor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("instruktor_id"));

                    b.Property<string>("biografia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("certifikimet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("data_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("specializimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("tarifa_orare")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("telefoni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("instruktor_id");

                    b.ToTable("Instruktoret");
                });

            modelBuilder.Entity("MyApp.Domain.Klasat", b =>
                {
                    b.Property<int>("klasa_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("klasa_id"));

                    b.Property<string>("emri_klases")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("instruktor_id")
                        .HasColumnType("int");

                    b.Property<int>("kapaciteti")
                        .HasColumnType("int");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("salla")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("klasa_id");

                    b.ToTable("Klasat");
                });

            modelBuilder.Entity("MyApp.Domain.Orari", b =>
                {
                    b.Property<int>("orari_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("orari_id"));

                    b.Property<string>("dita_javes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("klasa_id")
                        .HasColumnType("int");

                    b.Property<string>("ora_fillimit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ora_perfundimit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("salla_id")
                        .HasColumnType("int");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("orari_id");

                    b.ToTable("Orari");
                });

            modelBuilder.Entity("MyApp.Domain.Produktet", b =>
                {
                    b.Property<int>("produkti_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("produkti_id"));

                    b.Property<double>("cmimi")
                        .HasColumnType("double");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("kategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sasia_stock")
                        .HasColumnType("int");

                    b.HasKey("produkti_id");

                    b.ToTable("Produktet");
                });

            modelBuilder.Entity("MyApp.Domain.Regjistrimi_Workshop", b =>
                {
                    b.Property<int>("rw_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("rw_id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_regjistrimit")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("statusi_pageses")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("workshop_id")
                        .HasColumnType("int");

                    b.HasKey("rw_id");

                    b.ToTable("Regjistrimi_Workshop");
                });

            modelBuilder.Entity("MyApp.Domain.Salla", b =>
                {
                    b.Property<int>("salla_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("salla_id"));

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("kapaciteti")
                        .HasColumnType("int");

                    b.Property<string>("pajisjet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("salla_id");

                    b.ToTable("Salla");
                });

            modelBuilder.Entity("MyApp.Domain.Shitjet_Produkteve", b =>
                {
                    b.Property<int>("shitje_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("shitje_id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<double>("cmimi_total")
                        .HasColumnType("double");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("produkti_id")
                        .HasColumnType("int");

                    b.Property<int>("sasia")
                        .HasColumnType("int");

                    b.HasKey("shitje_id");

                    b.ToTable("Shitjet_Produkteve");
                });

            modelBuilder.Entity("MyApp.Domain.Workshop", b =>
                {
                    b.Property<int>("workshop_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("workshop_id"));

                    b.Property<double>("cmimi")
                        .HasColumnType("double");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("instruktor_id")
                        .HasColumnType("int");

                    b.Property<int>("kapaciteti")
                        .HasColumnType("int");

                    b.Property<DateTime>("ora_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ora_perfundimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titulli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("workshop_id");

                    b.ToTable("Workshop");
                });
#pragma warning restore 612, 618
        }
    }
}
