// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Infrastructure.Data;

#nullable disable

namespace MyApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Domain.Anetaresimet", b =>
                {
                    b.Property<int>("anetaresimi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("anetaresimi_id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<decimal>("cmimi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("data_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_mbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("lloji")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("anetaresimi_id");

                    b.HasIndex("anetar_id");

                    b.ToTable("Anetaresimet");
                });

            modelBuilder.Entity("MyApp.Domain.Anetaret", b =>
                {
                    b.Property<int>("anetar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("anetar_id"));

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("data_lindjes")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("data_regjistrimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gjinia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lloji_anetaresimit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefoni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("anetar_id");

                    b.ToTable("Anetaret");
                });

            modelBuilder.Entity("MyApp.Domain.Instruktoret", b =>
                {
                    b.Property<int>("instruktor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("instruktor_id"));

                    b.Property<string>("biografia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("certifikimet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("data_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("specializimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("tarifa_orare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("telefoni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("instruktor_id");

                    b.ToTable("Instruktoret");
                });

            modelBuilder.Entity("MyApp.Domain.Klasat", b =>
                {
                    b.Property<int>("klase_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("klase_id"));

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("instruktor_id")
                        .HasColumnType("int");

                    b.Property<int>("kapaciteti_max")
                        .HasColumnType("int");

                    b.Property<int>("kohezgjatja_min")
                        .HasColumnType("int");

                    b.Property<string>("lloji")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("niveli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("klase_id");

                    b.ToTable("Klasat");
                });

            modelBuilder.Entity("MyApp.Domain.Orari", b =>
                {
                    b.Property<int>("orar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("orar_id"));

                    b.Property<string>("dita_javes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("klasa_id")
                        .HasColumnType("int");

                    b.Property<string>("ora_fillimit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ora_perfundimit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("salla_id")
                        .HasColumnType("int");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("orar_id");

                    b.ToTable("Orari");
                });

            modelBuilder.Entity("MyApp.Domain.Pagesat", b =>
                {
                    b.Property<int>("pagese_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("pagese_id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<int>("anetaresim_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_pageses")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("metoda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("shuma")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("pagese_id");

                    b.HasIndex("anetar_id");

                    b.HasIndex("anetaresim_id");

                    b.ToTable("Pagesat");
                });

            modelBuilder.Entity("MyApp.Domain.Produktet", b =>
                {
                    b.Property<int>("produkti_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("produkti_id"));

                    b.Property<decimal>("cmimi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("kategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sasia_stok")
                        .HasColumnType("int");

                    b.HasKey("produkti_id");

                    b.ToTable("Produktet");
                });

            modelBuilder.Entity("MyApp.Domain.Regjistrimet", b =>
                {
                    b.Property<int>("regjistrim_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("regjistrim_id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("orar_id")
                        .HasColumnType("int");

                    b.Property<string>("shenimet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("regjistrim_id");

                    b.HasIndex("anetar_id");

                    b.HasIndex("orar_id");

                    b.ToTable("Regjistrimet");
                });

            modelBuilder.Entity("MyApp.Domain.Regjistrimi_Workshop", b =>
                {
                    b.Property<int>("rw_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("rw_id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("data_regjistrimit")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("statusi_pageses")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("workshop_id")
                        .HasColumnType("int");

                    b.HasKey("rw_id");

                    b.ToTable("Regjistrimet_Workshop");
                });

            modelBuilder.Entity("MyApp.Domain.Salla", b =>
                {
                    b.Property<int>("salla_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("salla_id"));

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("kapaciteti")
                        .HasColumnType("int");

                    b.Property<string>("pajisjet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("salla_id");

                    b.ToTable("Sallat");
                });

            modelBuilder.Entity("MyApp.Domain.Shitjet_Produkteve", b =>
                {
                    b.Property<int>("shitje_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("shitje_id"));

                    b.Property<int>("anetar_id")
                        .HasColumnType("int");

                    b.Property<decimal>("cmimi_total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("produkti_id")
                        .HasColumnType("int");

                    b.Property<int>("sasia")
                        .HasColumnType("int");

                    b.HasKey("shitje_id");

                    b.HasIndex("anetar_id");

                    b.HasIndex("produkti_id");

                    b.ToTable("Shitjet_Produkteve");
                });

            modelBuilder.Entity("MyApp.Domain.Workshop", b =>
                {
                    b.Property<int>("workshop_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("workshop_id"));

                    b.Property<decimal>("cmimi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("instruktor_id")
                        .HasColumnType("int");

                    b.Property<int>("kapaciteti")
                        .HasColumnType("int");

                    b.Property<DateTime>("ora_fillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ora_perfundimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titulli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("workshop_id");

                    b.ToTable("Workshopet");
                });

            modelBuilder.Entity("MyApp.Domain.Anetaresimet", b =>
                {
                    b.HasOne("MyApp.Domain.Anetaret", null)
                        .WithMany()
                        .HasForeignKey("anetar_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApp.Domain.Pagesat", b =>
                {
                    b.HasOne("MyApp.Domain.Anetaret", "Anetari")
                        .WithMany()
                        .HasForeignKey("anetar_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.Domain.Anetaresimet", "Anetaresimi")
                        .WithMany()
                        .HasForeignKey("anetaresim_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anetaresimi");

                    b.Navigation("Anetari");
                });

            modelBuilder.Entity("MyApp.Domain.Regjistrimet", b =>
                {
                    b.HasOne("MyApp.Domain.Anetaret", "Anetari")
                        .WithMany()
                        .HasForeignKey("anetar_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.Domain.Orari", "Orari")
                        .WithMany()
                        .HasForeignKey("orar_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anetari");

                    b.Navigation("Orari");
                });

            modelBuilder.Entity("MyApp.Domain.Shitjet_Produkteve", b =>
                {
                    b.HasOne("MyApp.Domain.Anetaret", "Anetari")
                        .WithMany()
                        .HasForeignKey("anetar_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.Domain.Produktet", "Produkti")
                        .WithMany("Shitjet")
                        .HasForeignKey("produkti_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anetari");

                    b.Navigation("Produkti");
                });

            modelBuilder.Entity("MyApp.Domain.Produktet", b =>
                {
                    b.Navigation("Shitjet");
                });
#pragma warning restore 612, 618
        }
    }
}
